### ISSUE TITLE
Get different databases to import / export to a common format (BRAPI and / or ICASA)

### ISSUE THREAD

**Issue by dlebauer** [PlantPhenoHack2017/HackTopics#5]
It seems that BRAPI is a data exchange format used by many databases and tools. The TERRA REF team would like to support this interface but has not run into a use case where it was necessary (yet). 

Another common interface we have discussed supporting is ICASA. ICASA data formats are used within the AgMIP (crop model intercomparison) community. Another useful project could be the ICASA <--> BRAPI interfaces. 

These, as well as some of the ontologies are summarized by @craig-willis here: https://docs.google.com/presentation/d/10aN_5whs8y9SOC8Y9Rj1kbWCfi7YG3yFyNqVX4JUr2U/edit#slide=id.p

I'd suggest starting with BRAPI since it sounds like the phenomics community already has interest / awareness of this. But I bring up ICASA because crop modeling is also of interest in the community. (Note that while ICASA can be used by many crop models, BETYdb can be used by many land surface models that include crop models).

**Examples of BRAPI support:**

* BMS supports BRAPI
* Lots of genomics databases (Cassavabase and similar) support BRAPI
* FieldBook plans to export as BRAPI 
* BETYdb plans to import and export BRAPI

**potential projects**

Depending on interest, developers could add BRAPI endpoints to their tools and begin importing / exporting data via this format. 

A clear objective would be to develop one (or more) of the planned DB --> BRAPI or BRAPI --> DB interfaces. For example, TERRA has two potential use cases:

* FieldBook --> BRAPI --> BETYdb https://github.com/terraref/reference-data/issues/85
* BETYdb --> BMS and / or BMS --> BETYdb

**Comment by ramonawalls** [comment]
I am chairing an AgBioData working group on data sharing. We are focusing on many of the same issues, and that working group could be a way to continue (in the short term) work on this topic after the hackathon. Please have a look at our notes so far: https://docs.google.com/document/d/1XfbdlJ7YIRXeTt3QZMbvJgjkFl7b5l-wiP0ZFSGsWjc/edit#heading=h.rpxvk75u3ei5

**Comment by dlebauer** [comment]
Folks at the hackathon are interested in seeing what having data from BETYdb exported via BRAPI would look like. @craig-willis and @gsrohde could you please work on a BETYdb --> BRAPI export for a day and present a prototype tomorrow?

If you need clarification please tag me and @ramonawalls.

The BRAPI repo is https://github.com/plantbreeding/API. I'll tag @jeback1 who is the primary contributor and @lukasmueller who is the lead to say hello and 'FYI'.

**Comment by gsrohde** [comment]
@dlebauer I'm not at all familiar with BRAPI.  Craig is in meetings until 2.

**Comment by dlebauer** [comment]
@gsrohde if you and @craig-willis can discuss this afternoon, that would be great. We are currently working on a mapping of terms in this [google sheet](https://docs.google.com/spreadsheets/d/1ykPJWi0kLSYXUV86U54E9SLuypBMoJUuJTkdpcxuU1g/edit#gid=0) and taking notes in [this doc](https://docs.google.com/document/d/1eCgKFdDC-nCgHYGgP0ynz57ND6pu0nbgrQRtgKTaTsg/edit).

**Comment by dlebauer** [comment]
@jeback1 and @lukasmueller were there any results from the BRAPI-MIAPPE mapping activity on the agenda from the Dec 2016 hackathon?
[3rd-BrAPI-hackaton-Agenda.pdf](https://github.com/PlantPhenoHack2017/HackTopics/files/777924/3rd-BrAPI-hackaton-Agenda.pdf)

**Comment by craig-willis** [comment]
@dlebauer Scott and I met and will start working on a set of mock responses to relevant BRAPI calls.   We were only able to find a few relevant mappings. As with my earlier comparison, the mappings are pretty loose given that BRAPI and BETY are targeting different use cases:

BRAPI=BETYdb
* Germplasm=Cultivar
* Crops=Species
* Trial=Experiment (new table)
* Study Observation=Trait  (observed variable + time and value)
* Observation variable=Variable
* Location=Site
* Study Layout=Site

As we've already discussed, BRAPI adopts the Crop Ontology model of Variable=trait + method + scale, which is different than BETY's trait=observed variable (+method) .

**Comment by dlebauer** [comment]
Brapi has been implemented terraref.org/brapi
